<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Need)</span></div>

## 1 Lists, Arrays & Dictionaries

### 1.1 Let’s compare

**Python Lists**

In [2]:
py_super_names = ["Black Widow", "Iron Man", "Doctor Strange"]
py_real_names = ["Natasha Romanoff", "Tony Stark", "Stephen Strange"]

**Numpy Arrays**

In [3]:
np_super_names = np.array(["Black Widow", "Iron Man", "Doctor Strange"])
np_real_names = np.array(["Natasha Romanoff", "Tony Stark", "Stephen Strange"])

**Dictionary**

In [4]:
superhero_info = {"Natasha Romanoff": "Black Widow",
                  "Tony Stark": "Iron Man",
                  "Stephen Strange": "Doctor Strange"
                  }

Dictionaries use a key and an associated value separated by a :

##### Notes:
- There are 3 ways to store data:
1. python lists --> py
2. numpy arrays --> np
3. dictionaries

### 1.2 Accessing data from a list (or array)

In [8]:
py_super_names = ["Black Widow", "Iron Man", "Doctor Strange"]
py_real_names = ["Natasha Romanoff", "Tony Stark", "Stephen Strange"]

print(py_real_names[0])

print(py_super_names[2])

Natasha Romanoff
Doctor Strange


##### Notes:
- Python starts counting from 0! 
- So Black Widow is 0, Iron Man is 1, Doctor Strange is 2. 


In [12]:
print(py_super_names[2]) 
# This is forward indexing
# We need to know how many variables are in the list
# beforehand in order to pinpoint its index.

print(py_super_names[-1])
# This is reverse indexing
# We don't need to know how many variables are in the list
# beforehand since this allows us to count from the back 
# of the list.

Doctor Strange
Doctor Strange


### 1.3 Accessing data from a dictionary

In [14]:
superhero_info = {"Natasha Romanoff": "Black Widow",
                  "Tony Stark": "Iron Man",
                  "Stephen Strange": "Doctor Strange"
                  }
print(superhero_info["Natasha Romanoff"])
# Dictionaries are able to access the value (aka superhero name) 
# using the real name as a key. 

Black Widow


In [16]:
superhero_info.keys()
# This is to access all keys.

dict_keys(['Natasha Romanoff', 'Tony Stark', 'Stephen Strange'])

In [18]:
superhero_info.values()
# This is to access all values.

dict_values(['Black Widow', 'Iron Man', 'Doctor Strange'])

### 1.4 Higher dimensional lists

In [19]:
py_superhero_info = [['Natasha Romanoff', 'Black Widow'],
                     ['Tony Stark', 'Iron Man'],
                     ['Stephen Strange', 'Doctor Strange']]

## 2 Lists vs. Arrays

### 2.1 Size

In [20]:
py_list_2d = [[1, "A"], [2, "B"], [3, "C"], [4, "D"],
              [5, "E"], [6, "F"], [7, "G"], [8, "H"],
              [9, "I"], [10, "J"]]

np_array_2d = np.array(py_list_2d)      # Reusing the Python list 
                                        # to create a NEW
                                        # NumPy array

**Usually we need to know how many elements are in a list.
We use len( ) to find this out.**

**2D Python Lists:**

In [21]:
len(py_list_2d)

10

**2D Numpy Arrays:**

In [22]:
len(np_array_2d)

10

In [23]:
np_array_2d.shape

(10, 2)

There is absence of brackets in the shape above. This is because shape is not a function. 

##### Notes:
- For lists and arrays, the order of the variables matters. 
- Lists and arrays offer more features than dictionaries. 


### 2.2 Arrays are fussy about type

In [24]:
py_list = [1, 1.5, 'A']
np.array(py_list)

array(['1', '1.5', 'A'], dtype='<U32')

##### Notes:
- Arrays like having a single data type, but lists are more accommodating. 

### 2.3 Adding a number

In [25]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)         # Reusing the Python list
                                     # to create a NEW
                                     # NumPy array


**Lists**

In [26]:
py_list + 10 # Won't work!

TypeError: can only concatenate list (not "int") to list

**Arrays**

In [27]:
np_array + 10

array([11, 12, 13, 14, 15])

### 2.4 Adding another list

In [28]:
py_list_1 = [1, 2, 3, 4, 5]
py_list_2 = [10, 20, 30, 40, 50]

np_array_1 = np.array(py_list_1)
np_array_2 = np.array(py_list_2)


**Lists**

In [29]:
py_list_1 + py_list_2

[1, 2, 3, 4, 5, 10, 20, 30, 40, 50]

**Arrays**

In [30]:
np_array_1 + np_array_2

array([11, 22, 33, 44, 55])

### 2.5 Multiplying by a Number

In [31]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)         

**Lists:**
- Multiplying by a number makes a list grow.

In [34]:
py_list*2

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

**Arrays:**
- An array multiplies its elements by the number. 

In [38]:
np_array*2

array([ 2,  4,  6,  8, 10])

### 2.6 Squaring

In [39]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)

**Lists**

In [40]:
py_list**2 # Won't work!

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

**Arrays**

In [42]:
np_array**2 # Works!!

array([ 1,  4,  9, 16, 25])

### 2.7 Asking questions

In [43]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)         

**List**

In [45]:
py_list == 3 # Asking if the python list is only the value '3'?

False

In [46]:
py_list > 3 # Won't work!

TypeError: '>' not supported between instances of 'list' and 'int'

**Arrays**

In [48]:
np_array == 3 
# Asks if the value is indeed 3 for every single element.

array([False, False,  True, False, False])

In [50]:
np_array > 3
# Asks for the values that are more than 3.

array([False, False, False,  True,  True])

### 2.8 Mathematics

In [51]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)         

**List**

In [52]:
sum(py_list)     # sum() is a base Python function

15

In [53]:
max(py_list)     # max() is a base Python function

5

In [54]:
min(py_list)     # min() is a base Python function

1

In [55]:
py_list.sum()   # Won't work!

AttributeError: 'list' object has no attribute 'sum'

**Arrays**

In [56]:
np_array.sum()

15

In [57]:
np_array.mean()

3.0

In [58]:
np_array.max()

5

In [59]:
np_array.min()

1

## Exercise 1 :  Total recall?

Purely from memory, jot down:

1. Two similarities between lists and arrays.
- Lists and arrays are both used to store data.
- _Both lists and arrays are mutable, meaning that an item can be edited and changed. 


2. Two differences between lists and arrays. 
- To use lists, Python module is required. To use arrays, NumPy module is required. 
- _Lists can consist of elements belonging to different data types._
- _Arrays can only consist of elements belonging to the same data type._ 
- _Lists cannot directly handle arithmetic operations._
- _Arrays can directly handle arithmetic operations._

 
^ found these online :)

3. What is a dictionary?
- A dictionary is another way of storing data. It holds values paired with a key e.g. you can type in the real name of the actor and output will be the superhero they play. 


## Exercise 2 :  Index me

In [75]:
py_list = ["a1", "b2", "c3", "d4", "e5", "f6", "g7", "h8", "i9", "j10"]
print(py_list[0])
print(py_list[2])
print(py_list[4])
print(py_list[6])
print(py_list[8])

a1
c3
e5
g7
i9


## Exercise 3 :  Capitalise Heros

In [97]:
superhero_info = {"Natasha Romanoff": "Black Widow",
                  "Tony Stark": "Iron Man",
                  "Stephen Strange": "Doctor Strange"
                 }

superhero_info['Tony Stark'] = superhero_info['Tony Stark'].upper()                  
superhero_info['Natasha Romanoff'] = superhero_info['Natasha Romanoff'].upper()                  
superhero_info['Stephen Strange'] = superhero_info['Stephen Strange'].upper()                  

print(superhero_info)

{'Natasha Romanoff': 'BLACK WIDOW', 'Tony Stark': 'IRON MAN', 'Stephen Strange': 'DOCTOR STRANGE'}


## Exercise 4 :  How many ones

In [124]:
py_list=[45, 60, 1, 30, 96, 1, 96, 57, 16, 1,
        99, 62, 86, 43, 42, 60, 59, 1, 1, 35,
        83, 47, 34, 28, 68, 23, 22, 92, 1, 79,
        1, 29, 94, 72, 46, 47, 1, 74, 32, 20,
        8, 37, 35, 1, 89, 29, 86, 19, 43, 61] 

np_array = np.array(py_list)

np_array <= 1 # Identify which number in the list are 1s 

new_np_array = np_array <= 1 # Make new_np_array equals to the number of 1s

new_np_array.sum() # sum total number of 1s present


9