<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Good)</span></div>

## 1 Subsetting: Indexing and Slicing

### 1.1 Indexing & Slicing 1D (Lists & Arrays)

In [2]:
py_list=["a1", "b2", "c3", "d4", "e5",
         "f6", "g7", "h8", "i9", "j10"]
np_array=np.array(py_list)

# Pick one
x = py_list  # OR
x = np_array

##### Notes:
- Subsetting = to 'select'.
- Indexing = to select one element in the list/array.
- Slicing = to select a range of elements in the list/array.
    - For slicing must indicate where to start and end by specifying two indices. 

##### Slicing Syntax:
| Syntax    | Result                                            | Note                                                 |
|-----------|---------------------------------------------------|------------------------------------------------------|
| x[0]      | First element ['a1']                              |                                                      |
| x[-1]     | Last element ['j10']                              |                                                      |
| x[0:3]    | Index 0 to 2 ['a1','b2','c3']                     | Gives   3 − 0 = 3 3 − 0 = 3  elements                |
| x[1:6]    | Index 1 to 5 ['b2','c3','d4','e5','f6']           | Gives   6 − 1 = 5 6 − 1 = 5  elements                |
| x[1:6:2]  | Index 1 to 5 in steps of 2 [' b1','d4','f6']      | Gives every other of   6 − 1 = 5 6 − 1 = 5  elements |
| x[5:]     | Index 5 to the end ['f6','g7','h8','i9','j10']    | Gives   len(x) − 5 = 5 − 5 = 5  elements             |
| x[:5]     | Index 0 to 5 ['a1','b2','c3','d4','e5']           | Gives   5 − 0 = 5 5 − 0 = 5  elements                |
| x[5:2:-1] | Index 5 to 3 (i.e. in reverse) ['f6','e5','d4']   | Gives   5 − 2 = 3 5 − 2 = 3  elements                |
| x[::-1]   | Reverses the list ['j10','i9','h8',...,'b2','a1'] | elements                                             |

**PS: If you slice with [ i : j ], the slice will start at i and end at j-i, giving you a total of j-i elements.**

### 1.2 Subsetting by masking (works for Arrays only)

In [3]:
np_array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
my_mask = np_array > 3
print(my_mask)

[False False False  True  True  True  True  True  True  True]


In [6]:
np_array[my_mask] # This asks NumPy to show only those 
                  # variables from the array above that are true

array([ 4,  5,  6,  7,  8,  9, 10])

##### Notes:
- Masking only works with NumPy arrays. 
- Masking is to allow only the True subset to be seen. First make the mask equal to variables in the array that are more than 3. Then ask to print to show which variables are false and true. 

- Then ask numpy to show only the variables that are true. 

In [7]:
np_array[np_array > 3]

array([ 4,  5,  6,  7,  8,  9, 10])

In [8]:
np_array[~(np_array > 3)]                   # '~' means 'NOT'

array([1, 2, 3])

In [9]:
np_array[(np_array > 3) & (np_array < 8)]         # '&' means 'AND'

array([4, 5, 6, 7])

In [10]:
np_array[(np_array < 3) | (np_array > 8)]         # '|' means 'OR'

array([ 1,  2,  9, 10])

##### Notes:
- In Bitwise,
- ( ~ ) is NOT.
- ( & ) is AND. 
- ( | ) is OR.

### 1.3 Indexing & Slicing 2D Lists

In [11]:
py_list_2d = [[1, "A"], [2, "B"], [3, "C"], [4, "D"],
              [5, "E"], [6, "F"], [7, "G"], [8, "H"],
              [9, "I"], [10, "J"]]

In [12]:
py_list_2d[3]        # What is at position 4 (index 3)?

[4, 'D']

In [13]:
py_list_2d[3][0]     # FIRST element at position 4 (index 3).

4

In [14]:
py_list_2d[:3]      # Index 0 to 3, 3-0=3 elements.

[[1, 'A'], [2, 'B'], [3, 'C']]

In [15]:
py_list_2d[:3][0]   # FIRST element between index 0 to 3. 

[1, 'A']

In [16]:
py_list_2d[3:6][0] # FIRST element between index 3 to 6. 

[4, 'D']

### 1.4 Indexing & Slicing 2D Arrays

In [22]:
np_array_2d = np.array([[1, "A"], [2, "B"], [3, "C"], [4, "D"],
                        [5, "E"], [6, "F"], [7, "G"], [8, "H"],
                        [9, "I"], [10, "J"]])

In [18]:
np_array_2d[3]       # What is at position 4 (index 3)?

array(['4', 'D'], dtype='<U21')

In [19]:
np_array_2d[3, 0]    # FIRST element at position 4 (index 3)

'4'

In [20]:
np_array_2d[:3]      # Index 0 to 3, 3-0 = 3 elements. 

array([['1', 'A'],
       ['2', 'B'],
       ['3', 'C']], dtype='<U21')

In [21]:
np_array_2d[:3, 0]    # FIRST elements of index 0 to 3. 

array(['1', '2', '3'], dtype='<U21')

In [25]:
np_array_2d[3:6, 0]   

# FIRST elements of index 3 to 6. 
# 3:6 --> index 3 to 6 --> [4, "D"], [5, "E"], [6, "F"]
# 0 --> first elements of... 


array(['4', '5', '6'], dtype='<U21')

In [24]:
np_array_2d[:, 0]     # FIRST elements of the whole list. 

array(['1', '2', '3', '4', '5', '6', '7', '8', '9', '10'], dtype='<U21')

### 1.5 Growing lists

In [26]:
x=[1]*10
x               # I am lazy to type print()
                # Let Jupyter do the hard work.

[1, 1, 1, 1, 1, 1, 1, 1, 1, 1]

In [27]:
x=[1]
x= x + [2]
x= x + [3]
x= x + [4]
x

[1, 2, 3, 4]

In [28]:
x=[1]
x+= [2]
x+= [3]
x+= [4]
x

[1, 2, 3, 4]

In [29]:
x=[1]
x+= [2, 3, 4]
x

[1, 2, 3, 4]

In [30]:
x=[1]
x= [2, 3, 4] + x
x

[2, 3, 4, 1]

In [31]:
x=[1]
x.append(2)
x.append(3)
x.append(4)
x

[1, 2, 3, 4]

In [1]:
x=[1]
x+= [2, 3, 4]
x

[1, 2, 3, 4]

In [33]:
x=[1]
x= [2, 3, 4] + x
x

[2, 3, 4, 1]

In [34]:
x=[1]
x.append(2)
x.append(3)
x.append(4)
x

[1, 2, 3, 4]

##### Notes:
- append( ) adds a list inside of a list. 
- .append( ) added another list into a list

## 2 Some loose ends

### 2.1 Tuples

##### Notes:
- Tuple = another data storage 
- Tuple are similar to lists but use ( ) and cannot be changed after creation.

In [35]:
a=(1, 2, 3)     # Define tuple

In [36]:
print(a[0])    # Access data

1


In [37]:
# However, we cannot change the data. 
# The following will NOT work
a[0]=-1
a[0] += [10]

TypeError: 'tuple' object does not support item assignment

### 2.2 Be VERY careful when copying

In [38]:
x=[1, 2, 3]
y=x           # DON'T do this!
z=x           # DON'T do this!

In [41]:
# The correct way to copy a list is:

x=[1, 2, 3]
y=x.copy()
z=x.copy()

## Exercise 1 :  Total recall?

| Term       | Brief description                                                                         |
|------------|-------------------------------------------------------------------------------------------|
| Subsetting | to 'select'                                                                               |
| Indexing   | to select one element from the list/_array_                                               |
| Slicing    | to select a range of elements from the list/_array_ (MUST SPECIFY START AND END OF RANGE) |
| Masking    | to only show variables that are true.  _only works for NumPy arrays._                     |

## Exercise 2 :  Show me the ‘odd’ letters

In [2]:
np_array_2d = np.array([[1, "A"], [3, "C"], [2, "B"], [4, "D"],
                        [5, "E"], [7, "G"], [6, "F"], [8, "H"],
                        [10, "J"], [9, "I"]])
np_array_2d[:, 0]     # step 1

array(['1', '3', '2', '4', '5', '7', '6', '8', '10', '9'], dtype='<U21')

In [4]:
np_array_2d[:, 0].astype(int)   # step 2

array([ 1,  3,  2,  4,  5,  7,  6,  8, 10,  9])

In [5]:
np_array_2d[:, 0].astype(int)%2   # step 3

array([1, 1, 0, 0, 1, 1, 0, 0, 0, 1])

In [10]:
np_array_2d[:, 0].astype(int)%2
my_mask = np_array_2d[:, 0].astype(int)%2 > 0
print(my_mask) # step 4

[ True  True False False  True  True False False False  True]


In [20]:
np_array_2d[my_mask, 1] # step 5

array(['A', 'C', 'E', 'G', 'I'], dtype='<U21')